spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db1.civc1qeitjb1.ap-northeast-2.rds.amazonaws.com:3306/board
    username: admin
    password: 1q2w3e4r
  mail:
    host: smtp.gmail.com
    port: 587
    username: tig01647@gmail.com
    password: drguohyuvsnrphbq
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

mybatis:
  mapper-locations:
    - /mappers/*.xml

# secret key (https://jwt-keys.21no.de/) 여기 넣는 이유 - 이 파일을 git 올릴 때 제외 할 수 있음
jwt:
  secret: zmO+uCu7SQs64GP4MivcdOIwNgqPFZffIMZpBnqAHPjPZdfGjxDp1WmFof3wcnoC0HdK12i2P3PXwiZtCeb21g==